channels:
  - anaconda
  - defaults
  - conda-forge
  - dmentipl
dependencies:
  - ipywidgets
  - ipympl
  - numpy
  - scipy
  - matplotlib
  - fastparquet
  - cmasher
  - joypy
  - seaborn
  - pandas
  - arviz
#  - geopandas
  - cartopy
  - bokeh>=2.4.0,<3.0
  - plotly>=4.0
  - holoviews
#Needs python <3.8
  - kdepy 
#  - altair
  - pygwalker
  - perspective
